---
# tasks file for ansible-polybar
- name: Make sure config directory exists
  file:
    path: "{{ansible_env.HOME}}/.config/polybar"
    state: directory

- name: Copy main polybar config
  copy:
    src: config
    dest: "{{ansible_env.HOME}}/.config/polybar/config"

- name: Copy external scripts
  copy:
    src: "{{item}}"
    dest: "{{ansible_env.HOME}}/.config/polybar/{{item}}"
    mode: 755
  with_items:
    - weather
    - mpris.sh
    - pkg.sh

- name: Make launch script directory exists
  file:
    path: "{{ansible_env.HOME}}/.local/bin"
    state: directory

- name: Copy launch script
  copy:
    src: launch_polybar
    dest: "{{ansible_env.HOME}}/.local/bin/launch_polybar"
    mode: 755
