---
# tasks file for ansible-polybar
- name: Make sure config directory exists
  file:
    path: "{{ansible_env.HOME}}/.config/polybar"
    state: directory

- name: Copy main polybar config
  copy:
    src: config
    dest: "{{ansible_env.HOME}}/.config/polybar/config"

- name: Copy external scripts
  copy:
    src: "{{item}}"
    dest: "{{ansible_env.HOME}}/.config/polybar/{{item}}"
  with_items:
    - weather
    - mpris.sh
    - pkg.sh


